---
title: "Augur Perturbation Analysis: Purkinje cells MANF KO Slide 3"
output: html_document
author: Michael Chimenti
date: 11.09.21
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, warning=FALSE, message=FALSE}
library(Seurat)
library(Augur)
library(tidyverse)
library(patchwork)
library(hdf5r)
```

### Sample 9 and 10

```{r, load_vis, message=FALSE, results=FALSE, eval=FALSE}
setwd('~/collab_proj/wen_wen/project_spatial_mouseKO_Aug2021')
s9 <- Load10X_Spatial(data.dir = 'sample9', filename = 'filtered_feature_bc_matrix.h5', filter.matrix = TRUE, assay = "Spatial")
s10 <- Load10X_Spatial(data.dir = 'sample10', filename = 'filtered_feature_bc_matrix.h5', filter.matrix = TRUE, assay = "Spatial")
```

```{r, sctransform, warning=FALSE, message=FALSE, results=FALSE, eval=FALSE}

s9$orig.ident <- "s9_cntrl"
s10$orig.ident <- "s10_knock"

#######
st.list <- list(control=s9,knockout=s10)
#######

st.list <- lapply(st.list, SCTransform, assay = "Spatial", method = "qpoisson")
options(future.globals.maxSize = 2000 * 1024^2) 
st.features = SelectIntegrationFeatures(st.list, nfeatures = 3000, verbose = FALSE)
st.list <- PrepSCTIntegration(object.list = st.list, anchor.features = st.features, 
    verbose = FALSE)
int.anchors <- FindIntegrationAnchors(object.list = st.list, normalization.method = "SCT", 
    verbose = FALSE, anchor.features = st.features)

######
s9s10.int <- IntegrateData(anchorset = int.anchors, normalization.method = "SCT", 
    verbose = FALSE)

########
rm(int.anchors, st.list)
gc()


```

```{r, dim_red, eval=FALSE}
s9s10.int = s9s10.int %>%
# Run principal component analysis
RunPCA(npcs = 50, verbose = F) %>%
# Embed in two dimensions
RunUMAP(dims = 1:50, do.fast = T)

```

```{r, clust, eval=TRUE}

#setwd('~/collab_proj/wen_wen/project_spatial_mouseKO_Aug2021')
###########
#saveRDS(s9s10.int, file = "s9_s10_integrated.rds")  ## Object saved; Note: Update this object before final report.  
###########
#s9s10.int <- readRDS("s9_s10_integrated.rds")


########
s9s10.int = s9s10.int %>%
FindNeighbors(dims = 1:11) %>%
FindClusters(resolution = 0.5)
########

DimPlot(s9s10.int, reduction = "umap", group.by = c("ident", "orig.ident"))
FeaturePlot(s9s10.int, features="Calb1", cols = c("Blue", "Red"))
SpatialFeaturePlot(s9s10.int, features = "Calb1")
SpatialDimPlot(s9s10.int, group.by = c("ident"), alpha = 0.7, cols = "Paired", label = TRUE)
```

### Cell type annotation 
```{r, celltype_prior_}
#########
s9s10.int = RenameIdents(s9s10.int,
`8` = "Purkinje",
`2` = "MolecularLayer",
`3` = "GranularLayer",
`10` = "ChoroidPlexus",
`7` = "White Matter")

# Add cell type annotations into the metadata of the Seurat object
s9s10.int$cell_type = Idents(s9s10.int)
DefaultAssay(s9s10.int) <- "SCT"

augur_9_10 <- Augur::calculate_auc(s9s10.int, label_col = "orig.ident", cell_type_col = "cell_type", 
                              n_threads = 4, 
                              rf_params = list(trees = 15, mtry = 2, min_n = NULL, importance = "accuracy"),
                              n_subsamples = 20,
                              )


```

```{r, viz_augur}
augur_9_10$AUC

### Transfer AUC results into Seurat Object for plotting
auc_tab <- augur_9_10$AUC
auc_tab$rank <- c(1:11)
tib <- s9s10.int$cell_type %>% as_tibble(rownames = "Barcode") %>% rename(cell_type=value)
tib <- tib %>% left_join(., auc_tab)
s9s10.int$AUC <- round(tib$auc, 3) 
s9s10.int$RANK <- tib$rank

assertthat::are_equal(colnames(s9s10.int), tib$Barcode)

SpatialDimPlot(s9s10.int, group.by = "AUC", cols = rev(c("#D73027", "#F46D43", "#FDAE61", "#FEE090", "#FFFFBF", "#E0F3F8", "#ABD9E9", "#74ADD1", "#4575B4")))

#####

p1 <- plot_umap(augur_9_10, s9s10.int, mode = "default", palette = "Spectral")
p1 <- p1 + geom_point(size=0.2) + ggtitle("Augur Perturbation by Type (Red = Most)")


p2 <- DimPlot(s9s10.int, reduction = "umap", group.by = "cell_type") + ggtitle("Sample 9/10 integrated Cell Types")
p1 + p2
```

### Samples 11 and 12

```{r, load_vis, message=FALSE, results=FALSE, eval=FALSE}
setwd('~/collab_proj/wen_wen/project_spatial_mouseKO_Aug2021')

s11 <- Load10X_Spatial(data.dir = 'sample11', filename = 'filtered_feature_bc_matrix.h5', filter.matrix = TRUE, assay = "Spatial")
s12 <- Load10X_Spatial(data.dir = 'sample12', filename = 'filtered_feature_bc_matrix.h5', filter.matrix = TRUE, assay = "Spatial")
```

```{r, sctransform, warning=FALSE, message=FALSE, results=FALSE, eval=FALSE}

s11$orig.ident <- "s11_cntrl"
s12$orig.ident <- "s12_knock"

#######
st.list <- list(control=s11,knockout=s12)
#######

st.list <- lapply(st.list, SCTransform, assay = "Spatial", method = "qpoisson")
options(future.globals.maxSize = 2000 * 1024^2) 
st.features = SelectIntegrationFeatures(st.list, nfeatures = 3000, verbose = FALSE)
st.list <- PrepSCTIntegration(object.list = st.list, anchor.features = st.features, 
    verbose = FALSE)
int.anchors <- FindIntegrationAnchors(object.list = st.list, normalization.method = "SCT", 
    verbose = FALSE, anchor.features = st.features)

######
s11s12.int <- IntegrateData(anchorset = int.anchors, normalization.method = "SCT", 
    verbose = FALSE)

########
rm(int.anchors, st.list)
gc()


```

```{r, dim_red, eval=FALSE}
s11s12.int = s910.int %>%
# Run principal component analysis
RunPCA(npcs = 50, verbose = F) %>%
# Embed in two dimensions
RunUMAP(dims = 1:50, do.fast = T)

```

```{r, clust, eval=TRUE}

setwd('~/collab_proj/wen_wen/project_spatial_mouseKO_Aug2021')
###########
#saveRDS(s11s12.int, file = "s1_s2_integrated.rds")  ## Object saved; Note: Update this object before final report.  
###########
#s11s12.int <- readRDS("s1_s2_integrated.rds")


########
s11s12.int = s11s12.int %>%
FindNeighbors(dims = 1:10) %>%
FindClusters(resolution = 0.4)
########

DimPlot(s11s12.int, reduction = "umap", group.by = c("ident", "orig.ident"))
FeaturePlot(s11s12.int, features="Calb1", cols = c("Blue", "Red"))
SpatialFeaturePlot(s11s12.int, features = "Calb1")
SpatialDimPlot(s11s12.int, group.by = c("ident"), alpha = 0.7, cols = "Paired", label = TRUE)
```

### Cell type annotation 
```{r, celltype_prior_}
#########
s11s12.int = RenameIdents(s11s12.int,
`6` = "Purkinje",
`4` = "MolecularLayer",
`2` = "GranularLayer",
`10` = "ChoroidPlexus",
`1` = "White Matter",
`7` = "DCN",
`8` = "DCN",
`9` = "Brain Stem",
`11` = "Unk",
`12` = "Unk",
`13` = "Brain Stem")

# Add cell type annotations into the metadata of the Seurat object
s11s12.int$cell_type = Idents(s11s12.int)
DefaultAssay(s11s12.int) <- "SCT"

augur_11_12 <- Augur::calculate_auc(s11s12.int, label_col = "orig.ident", cell_type_col = "cell_type", 
                              n_threads = 6, 
                              rf_params = list(trees = 25, mtry = 2, min_n = NULL, importance = "accuracy"),
                              n_subsamples = 40,
                              )


```

```{r, viz_augur}

### Transfer AUC results into Seurat Object for plotting
auc_tab <- augur_11_12$AUC
auc_tab$rank <- c(1:9)
tib <- s11s12.int$cell_type %>% as_tibble(rownames = "Barcode") %>% rename(cell_type=value)
tib <- tib %>% left_join(., auc_tab)
s11s12.int$AUC <- round(tib$auc, 3) 
s11s12.int$RANK <- tib$rank

assertthat::are_equal(colnames(s11s12.int), tib$Barcode)

SpatialDimPlot(s11s12.int, group.by = "AUC", cols = rev(c("#D73027", "#F46D43", "#FDAE61", "#FEE090", "#FFFFBF", "#E0F3F8", "#ABD9E9", "#74ADD1", "#4575B4")))

#####

p1 <- plot_umap(augur_11_12, s11s12.int, mode = "default", palette = "Spectral")
p1 <- p1 + geom_point(size=0.2) + ggtitle("Augur Perturbation by Type (Red = Most)")


p2 <- DimPlot(s11s12.int, reduction = "umap", group.by = "cell_type") + ggtitle("Sample 9/10 integrated Cell Types")
p1 + p2
```

```{r, seshInfo}
sessionInfo()
```


